language: python
cache: pip

python:
    - "3.6"

sudo: false

env:
    - DJANGO=2.0

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=2.0 }

      - python: "3.6"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - tox  # test sdist

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
